package rak.pixellwp.cycling

const val LEFT = "cyclingLeft"
const val TOP = "cyclingTop"
const val RIGHT = "cyclingRight"
const val BOTTOM = "cyclingBottom"
const val SCALE_FACTOR = "cyclingScaleFactor"
const val PARALLAX = "parallax"
const val IMAGE_COLLECTION = "imageCollection"
const val IMAGE_TYPE = "imageType"
const val SINGLE_IMAGE = "singleImage"
const val LAST_HOUR_CHECKED = "lastHourChecked"
const val TIMELINE_IMAGE = "timelineImage"
const val OVERRIDE_TIMELINE = "overrideTimelines"
const val OVERRIDE_TIME_PERCENT = "dayPercent"
const val OVERRIDE_TIME = "overrideTime"
const val ADJUST_MODE = "adjustMode"